      - name: Run Flyway Migrate
        run: |
          echo "ðŸ§© Running Flyway migrations..."
          docker run --rm \
            --network host \
            -v "${{ github.workspace }}/migrations:/flyway/sql" \
            redgate/flyway \
            -locations=filesystem:/flyway/sql \
            -url=jdbc:mysql://127.0.0.1:3306/flyway_test \
            -user=root \
            -password=Secret5555 \
            migrate

      - name: Run Flyway Validate (optional)
        run: |
          docker run --rm \
            --network host \
            -v "${{ github.workspace }}/migrations:/flyway/sql" \
            redgate/flyway \
            -locations=filesystem:/flyway/sql \
            -url=jdbc:mysql://127.0.0.1:3306/flyway_test \
            -user=root \
            -password=Secret5555 \
            validate
